### ISSUE TITLE
Launching multi-gpu training without slurm

### ISSUE THREAD

**Issue by ashaw596** [facebookresearch/flow_matching#20]
Is there any easy way to launch multi-gpu training on the examples without slurm without refactoring everything?

**Comment by mhavasi** [comment]
The `examples/image` codebase is designed to run one process per gpu. 

You try modifying the submitit launcher to launch a local job instead of a slurm job. You need to use the LocalExecutor instead of AutoExecutor in `submitit_train.py`. (https://github.com/facebookincubator/submitit/blob/main/submitit/local/local.py#L125) 

Or you can try something like:
```
python -m torch.distributed.launch --nproc_per_node=8 train.py
```
or
```
torchrun --nproc_per_node=8 train.py
```

But we haven't tested these solutions and don't officially support them.

**Comment by sunovivid** [comment]
`torchrun --nproc_per_node=8 train.py` works for me.

Full `.sh` code I used:
```
export IMAGENET_DIR=~/flow_matching/examples/image/data/
export IMAGENET_RES=64
export CUDA_DEVICE_ORDER=PCI_BUS_ID
export CUDA_VISIBLE_DEVICES=0,1,2,3

torchrun --nproc_per_node=4 train.py --data_path=${IMAGENET_DIR}/train_${IMAGENET_RES}/box/
```

**Comment by Carton22** [comment]
@sunovivid 
Hello, I wonder how long it takes for your training?
